/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as CertRunIdRouteImport } from './routes/cert.$runId'
import { Route as StudioIndexRouteImport } from './routes/studio.index'
import { Route as StudioRunIdRouteImport } from './routes/studio.$runId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const CertRunIdRoute = CertRunIdRouteImport.update({
  id: '/cert/$runId',
  path: '/cert/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRoute,
} as any)
const StudioRunIdRoute = StudioRunIdRouteImport.update({
  id: '/$runId',
  path: '/$runId',
  getParentRoute: () => StudioRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/research': typeof ResearchRoute
  '/studio': typeof StudioRouteWithChildren
  '/cert/$runId': typeof CertRunIdRoute
  '/studio/$runId': typeof StudioRunIdRoute
  '/studio/': typeof StudioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/research': typeof ResearchRoute
  '/cert/$runId': typeof CertRunIdRoute
  '/studio/$runId': typeof StudioRunIdRoute
  '/studio': typeof StudioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/research': typeof ResearchRoute
  '/studio': typeof StudioRouteWithChildren
  '/cert/$runId': typeof CertRunIdRoute
  '/studio/$runId': typeof StudioRunIdRoute
  '/studio/': typeof StudioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/research'
    | '/studio'
    | '/cert/$runId'
    | '/studio/$runId'
    | '/studio/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/research' | '/cert/$runId' | '/studio/$runId' | '/studio'
  id:
    | '__root__'
    | '/'
    | '/research'
    | '/studio'
    | '/cert/$runId'
    | '/studio/$runId'
    | '/studio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResearchRoute: typeof ResearchRoute
  StudioRoute: typeof StudioRouteWithChildren
  CertRunIdRoute: typeof CertRunIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cert/$runId': {
      id: '/cert/$runId'
      path: '/cert/$runId'
      fullPath: '/cert/$runId'
      preLoaderRoute: typeof CertRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/$runId': {
      id: '/studio/$runId'
      path: '/$runId'
      fullPath: '/studio/$runId'
      preLoaderRoute: typeof StudioRunIdRouteImport
      parentRoute: typeof StudioRoute
    }
  }
}

interface StudioRouteChildren {
  StudioRunIdRoute: typeof StudioRunIdRoute
  StudioIndexRoute: typeof StudioIndexRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioRunIdRoute: StudioRunIdRoute,
  StudioIndexRoute: StudioIndexRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResearchRoute: ResearchRoute,
  StudioRoute: StudioRouteWithChildren,
  CertRunIdRoute: CertRunIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
